# The builder image, used to build the virtual environment
FROM python:3.11-buster as builder

RUN pip install poetry==1.8.3

ENV POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_IN_PROJECT=1 \
  POETRY_VIRTUALENVS_CREATE=1 \
  POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /electra

COPY pyproject.toml poetry.lock ./
RUN touch README.md

RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR

# The runtime image, used to just run the code provided its virtual environment
FROM python:3.11-slim-buster as runtime

# Install runtime dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  libgomp1 \
  libgl1-mesa-glx \
  libglib2.0-0 \
  && rm -rf /var/lib/apt/lists/*

RUN useradd -m electra-user

ENV PYTHONDONTWRITEBYTECODE=1 \
  PYTHONUNBUFFERED=1 \
  VIRTUAL_ENV=/electra/.venv \
  PATH="/electra/.venv/bin:$PATH"

COPY --from=builder ${VIRTUAL_ENV} ${VIRTUAL_ENV}

COPY app ./app
COPY electra_package electra_package


# Change ownership of the app directory to the non-root user
RUN chown -R electra-user:electra-user /app

# Switch to non-root user
USER electra-user

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

